// Countries
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_WWStats = 'GET_WWStats';
export const SET_ALL_COUNTRIES_LOADING = 'SET_ALL_COUNTRIES_LOADING';
export const ERROR = 'ERROR';
// Current Country
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';
export const SET_CURRENT_COUNTRY_LOADING = 'SET_CURRENT_COUNTRY_LOADING';
export const SET_CURRENT_COUNTRY_ERROR = 'SET_CURRENT_COUNTRY_ERROR';
// History
export const GET_HiSTORY_CURRENT_COUNTRY = 'GET_HiSTORY_CURRENT_COUNTRY';
export const GET_WW_DATA_HISTORY = 'GET_WW_DATA_HISTORY';
export const CLEAR_CURRENT_COUNTRY = 'CLEAR_CURRENT_COUNTRY';
export const SET_HiSTORY_CURRENT_COUNTRY_LOADING =
  'SET_HiSTORY_CURRENT_COUNTRY_LOADING';
export const SET_HiSTORY_CURRENT_COUNTRY_ERROR =
  'SET_HiSTORY_CURRENT_COUNTRY_ERROR';
